# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: your_org
# "service" is the name of this project. This will also be added to your AWS resource names.
service: your_services




provider:
  name: your_file_name
  runtime: nodejs20.x
  memorySize: 128
  region: your_aws_region
  stage: ${opt:stage, 'dev'}
  httpApi:
    cors: true



functions:
  createUser:
    handler: src/handlers/createUser.handler
    events:
      - httpApi:
          path: /users
          method: POST


  getUser:
    handler: src/handlers/getUser.handler
    events:
      - httpApi:
          path: /users/{email}
          method: GET


  getAll:
    handler: src/handlers/getAll.handler
    events:
      - httpApi:
          path: /users
          method: GET



  updateUser:
    handler: src/handlers/updateUser.handler
    events:
      - httpApi:
          path: /users/{email}
          method: PUT





  deleteUser:
    handler: src/handlers/deleteUser.handler
    events:
      - httpApi:
          path: /users/{email}
          method: DELETE





plugins:
  - serverless-dotenv-plugin
  - serverless-offline










